### ISSUE TITLE
OPE-D Evaluation Related Code?

### ISSUE THREAD

**Issue by bryanzhou008** [matteo-dunnhofer/fpv-tracking-baselines#1]
Congratulations on the great work! I'm very interested in your work and evaluations. Would you be able to share the code described in the paper about OPE-D Evaluations? Thank you very much!

**Comment by matteo-dunnhofer** [comment]
Hi @bryanzhou008, I am currently busy with other research activities and I do not have the time to clean the OPE-D code. I will try to upload it experiments as soon as possible. In the mean time, you can try to run the object detectors we used (https://github.com/ddshan/hand_object_detector and https://data.bris.ac.uk/data/dataset/6016a974fcb3113b6173ff638dc6f7bb) on TREK-150's and use the earliest prediction having overlap > 0.5 to initialise the tracker.
