### ISSUE TITLE
Can't run LTMU-H baseline evals for TREK-150: what's going on?

### ISSUE THREAD

**Issue by vineetparikh** [matteo-dunnhofer/fpv-tracking-baselines#2]
I'm testing out LTMU-H for TREK-150 and finding that even after setting up 100DoH and the LTMU setup + extracting and running TREK-150 (and verifying that the rest of the toolkit works), I'm unable to run evaluation for LTMU-H because the HIC detector python file doesn't seem to register the "model" package correctly. Basically the error is happening here:
```
import sys
sys.path.append('./hand_object_detector')
from model.utils.config import cfg, cfg_from_file, cfg_from_list, get_output_dir
from model.rpn.bbox_transform import clip_boxes
from model.roi_layers import nms
from model.rpn.bbox_transform import bbox_transform_inv
from model.utils.net_utils import filter_object, save_net, load_net, vis_detections, vis_detections_PIL, vis_detections_filtered_objects_PIL, vis_detections_filtered_objects # (1) here add a function to viz
from model.utils.blob import im_list_to_blob
from model.faster_rcnn.vgg16 import vgg16
from model.faster_rcnn.resnet import resnet
```
with the actual error being 
```
Traceback (most recent call last):
  File "/home/vap43/fpv-tracking-baselines/LTMU-H/evaluate_trek150.py", line 4, in <module>
    from ltmuh import LTMUH
  File "/home/vap43/fpv-tracking-baselines/LTMU-H/ltmuh.py", line 30, in <module>
    from hic_detector import hic_config, hic_detect
  File "/home/vap43/fpv-tracking-baselines/LTMU-H/./hic_detector.py", line 13, in <module>
    from model.utils.config import cfg, cfg_from_file, cfg_from_list, get_output_dir
ModuleNotFoundError: No module named 'model.utils'; 'model' is not a package
```

Any idea what's going on? I'm looking to use this for a downstream task but am confused as to why the HIC is failing on this import: is there some setup issue?

**Comment by vineetparikh** [comment]
looks like this was because I needed to install faster-rcnn as a requirement from 100DoH (i.e. needed to rerun `pip install -r requirements.txt` separately after making the conda env). I'll close this now, but if people have questions about what I needed to do please let me know!

**Comment by xinfei-wang** [comment]
"I'm also encountering this issue. How did you resolve it?"

**Comment by xinfei-wang** [comment]
> I'm testing out LTMU-H for TREK-150 and finding that even after setting up 100DoH and the LTMU setup + extracting and running TREK-150 (and verifying that the rest of the toolkit works), I'm unable to run evaluation for LTMU-H because the HIC detector python file doesn't seem to register the "model" package correctly. Basically the error is happening here:
> 
> ```
> import sys
> sys.path.append('./hand_object_detector')
> from model.utils.config import cfg, cfg_from_file, cfg_from_list, get_output_dir
> from model.rpn.bbox_transform import clip_boxes
> from model.roi_layers import nms
> from model.rpn.bbox_transform import bbox_transform_inv
> from model.utils.net_utils import filter_object, save_net, load_net, vis_detections, vis_detections_PIL, vis_detections_filtered_objects_PIL, vis_detections_filtered_objects # (1) here add a function to viz
> from model.utils.blob import im_list_to_blob
> from model.faster_rcnn.vgg16 import vgg16
> from model.faster_rcnn.resnet import resnet
> ```
> 
> with the actual error being
> 
> ```
> Traceback (most recent call last):
>   File "/home/vap43/fpv-tracking-baselines/LTMU-H/evaluate_trek150.py", line 4, in <module>
>     from ltmuh import LTMUH
>   File "/home/vap43/fpv-tracking-baselines/LTMU-H/ltmuh.py", line 30, in <module>
>     from hic_detector import hic_config, hic_detect
>   File "/home/vap43/fpv-tracking-baselines/LTMU-H/./hic_detector.py", line 13, in <module>
>     from model.utils.config import cfg, cfg_from_file, cfg_from_list, get_output_dir
> ModuleNotFoundError: No module named 'model.utils'; 'model' is not a package
> ```
> 
> Any idea what's going on? I'm looking to use this for a downstream task but am confused as to why the HIC is failing on this import: is there some setup issue?

**Comment by xinfei-wang** [comment]
sys.path.append('./hand_object_detector')
import _init_paths
from model.utils.config import cfg, cfg_from_file, cfg_from_list, get_output_dir
